package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "coding",
    srcs = ["main.cc"],
    copts = [
        "-std=c++17",
        "-g",
    ],
)
cc_binary(
    name = "findK",
    srcs = ["findK.cc"],
    copts = [
        "-std=c++17",
        "-g",
    ],
)
cc_binary(
    name = "demo",
    srcs = ["demo.cc"],
    copts = [
        "-std=c++17",
        "-g",
    ],
)


cc_binary(
    name = "leetcode1",
    srcs = ["leetcode1.cc"],
    copts = [
        "-std=c++17",
        "-g",
    ],
)
