package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "union",
    srcs = ["union.cc"],
    copts = [
        "-std=c++17",
        "-g",
    ],
)


cc_binary(
    name = "explicit",
    srcs = ["explicit.cc"],
    copts = [
        "-std=c++17",
        "-g",
    ],
)


cc_binary(
    name = "polymorphism",
    srcs = ["polymorphism.cc"],
    copts = [
        "-std=c++17",
        "-g",
    ],
)
