package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "cast",
    srcs = ["cast.cc"],
    copts = [
        "-std=c++17",
    ],
)

cc_binary(
    name = "virtual",
    srcs = ["virtual.cc"],
    copts = [
        "-std=c++17",
    ],
)

cc_binary(
    name = "virtual_base_class",
    srcs = ["virtual_base_class.cc"],
    copts = [
        "-std=c++17",
    ],
)